[[CCCL_C]]
arch = "x86_64"
cuda = "12.8"
git-tree-sha1 = "1a4af1ba520fac95edfcf066d78e7e532e54f427"
libc = "glibc"
os = "linux"

    [[CCCL_C.download]]
    sha256 = "26e46e6c72e15490808a17be4f73cb4826140125c30d90e42ea382359997050d"
    url = "https://github.com/JuliaBinaryWrappers/CCCL_C_jll.jl/releases/download/CCCL_C-v3.5.0+0/CCCL_C.v3.5.0.x86_64-linux-gnu-cuda+12.8.tar.gz"
[[CCCL_C]]
arch = "aarch64"
cuda = "12.8"
cuda_platform = "jetson"
git-tree-sha1 = "7873062e2dd8bbc9ef3cf863fb42faa81968476c"
libc = "glibc"
os = "linux"

    [[CCCL_C.download]]
    sha256 = "928f6b97d2fee96ba4bdd3cc104bfb133956d1c13906421383e04cfdf802914a"
    url = "https://github.com/JuliaBinaryWrappers/CCCL_C_jll.jl/releases/download/CCCL_C-v3.5.0+0/CCCL_C.v3.5.0.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.8.tar.gz"
[[CCCL_C]]
arch = "aarch64"
cuda = "12.8"
cuda_platform = "sbsa"
git-tree-sha1 = "a58cd80b6a9c155d247e64cef0801fda2a5c789e"
libc = "glibc"
os = "linux"

    [[CCCL_C.download]]
    sha256 = "c1054c2697e22efa5161ee0fdddaf65a6f3ec4b03d0dcc09ee1fb339831ca30e"
    url = "https://github.com/JuliaBinaryWrappers/CCCL_C_jll.jl/releases/download/CCCL_C-v3.5.0+0/CCCL_C.v3.5.0.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.8.tar.gz"
[[CCCL_C]]
arch = "x86_64"
cuda = "12.8"
git-tree-sha1 = "13ef1ad12af3ffe559ab876c989941f300a33ca9"
os = "windows"

    [[CCCL_C.download]]
    sha256 = "709a75f3a6a73db884179cdf6abdbe19e5a4513676bf1cba91038eb7c3432a32"
    url = "https://github.com/JuliaBinaryWrappers/CCCL_C_jll.jl/releases/download/CCCL_C-v3.5.0+0/CCCL_C.v3.5.0.x86_64-w64-mingw32-cuda+12.8.tar.gz"
[[CCCL_C]]
arch = "x86_64"
cuda = "13.0"
git-tree-sha1 = "1c4fa7bd28f7cfbc2d479116cd72860f8abc38e4"
libc = "glibc"
os = "linux"

    [[CCCL_C.download]]
    sha256 = "f88fd86610dfba77d3f72e471c166b20141c3d0b6ef8ea0f583fd3165d267adf"
    url = "https://github.com/JuliaBinaryWrappers/CCCL_C_jll.jl/releases/download/CCCL_C-v3.5.0+0/CCCL_C.v3.5.0.x86_64-linux-gnu-cuda+13.0.tar.gz"
[[CCCL_C]]
arch = "aarch64"
cuda = "13.0"
git-tree-sha1 = "1d106b4ca2d0693536582c7ad19c669ccbca5ce2"
libc = "glibc"
os = "linux"

    [[CCCL_C.download]]
    sha256 = "29dcfbc897fa1c74a007603b33604cd535535e0f4746f1eb3fd740da8aaf26c1"
    url = "https://github.com/JuliaBinaryWrappers/CCCL_C_jll.jl/releases/download/CCCL_C-v3.5.0+0/CCCL_C.v3.5.0.aarch64-linux-gnu-cuda+13.0.tar.gz"
[[CCCL_C]]
arch = "x86_64"
cuda = "13.0"
git-tree-sha1 = "c32977d77b085397ab26e5a7396b995e5327762d"
os = "windows"

    [[CCCL_C.download]]
    sha256 = "de125d95ba03b8889cb8acc498bade320141524475aa2cd6ce88885609ad4bcb"
    url = "https://github.com/JuliaBinaryWrappers/CCCL_C_jll.jl/releases/download/CCCL_C-v3.5.0+0/CCCL_C.v3.5.0.x86_64-w64-mingw32-cuda+13.0.tar.gz"
