# Autogenerated wrapper script for CCCL_C_jll for aarch64-linux-gnu-cuda_platform+jetson-cuda+12.8
export cccl_c_header, cub_version_header, libcccl_c_parallel, libcudacxx_version_header, thrust_version_header

using CompilerSupportLibraries_jll
using CUDA_Compiler_jll
JLLWrappers.@generate_wrapper_header("CCCL_C")
JLLWrappers.@declare_file_product(cccl_c_header)
JLLWrappers.@declare_file_product(cub_version_header)
JLLWrappers.@declare_library_product(libcccl_c_parallel, "libcccl.c.parallel.so")
JLLWrappers.@declare_file_product(libcudacxx_version_header)
JLLWrappers.@declare_file_product(thrust_version_header)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, CUDA_Compiler_jll)
    JLLWrappers.@init_file_product(
        cccl_c_header,
        "include/cccl/c/reduce.h",
    )

    JLLWrappers.@init_file_product(
        cub_version_header,
        "include/cub/version.cuh",
    )

    JLLWrappers.@init_library_product(
        libcccl_c_parallel,
        "lib/libcccl.c.parallel.so",
        nothing,
    )

    JLLWrappers.@init_file_product(
        libcudacxx_version_header,
        "include/cuda/std/version",
    )

    JLLWrappers.@init_file_product(
        thrust_version_header,
        "include/thrust/version.h",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
